title: symfinder Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ternava.github.io

aux_links:
  Template Repository: https://github.com/ternava/sym-docs
